# Generated by Django 4.1.7 on 2023-04-17 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': (('can_add_employee', 'can add employee'),)},
        ),
    ]
