# Generated by Django 4.1.7 on 2023-04-17 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
    ]
